# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

#       - name: Setup yarn
#         uses: borales/actions-yarn@v2.3.0
#         with:
#           cmd: config set ignore-engines true

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Continuous Integration
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: ci

      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
